/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Obsidian Telemetry Design System Tokens
        "surface-tint": "#00daf3",
        "surface-container-highest": "#2f3542",
        "surface-variant": "#2f3542",
        "on-tertiary": "#003824",
        "on-error": "#690005",
        "on-background": "#dde2f4",
        "secondary-container": "#00a6e0",
        "surface-container-low": "#161c28",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#004f58",
        "on-surface-variant": "#bac9cc",
        "surface-bright": "#333947",
        "primary-fixed": "#9cf0ff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-high": "#242a37",
        "surface-container": "#1a202c",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00374d",
        "background": "#0d131f",
        "inverse-surface": "#dde2f4",
        "on-tertiary-container": "#006645",
        "inverse-primary": "#006875",
        "surface-dim": "#0d131f",
        "outline": "#849396",
        "surface": "#0d131f",
        "on-primary-container": "#00626e",
        "on-surface": "#dde2f4",
        "primary-container": "#00e5ff",
        "secondary": "#7bd0ff",
        "outline-variant": "#3b494c",
        "tertiary": "#a8ffd2",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed-variant": "#004c69",
        "tertiary-container": "#5be9ad",
        "on-secondary": "#00354a",
        "primary": "#c3f5ff",
        "surface-container-lowest": "#080e1a",
        "on-primary-fixed": "#001f24",
        "error-container": "#93000a",
        "on-secondary-fixed": "#001e2c",
        "on-tertiary-fixed": "#002113",
        "error": "#ff5370",
        "secondary-fixed": "#c4e7ff",
        "primary-fixed-dim": "#00daf3",
        "on-primary": "#00363d",
        "inverse-on-surface": "#2a303e",
        "on-tertiary-fixed-variant": "#005236",

        // Command Center Legacy & Semantic Aliases
        command: {
          bg: '#0a0e17',
          surface: '#111827',
          card: '#161f30',
          border: '#223049',
          accent: '#06b6d4',
          highlight: '#38bdf8',
          danger: '#ef4444',
          warning: '#f59e0b',
          success: '#10b981',
          critical: '#dc2626'
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter-md": "1.5rem",
        "space-md": "1rem",
        margin: "1rem",
        "margin-lg": "3rem",
        "space-xl": "2.5rem",
        gutter: "1rem",
        "space-lg": "1.5rem",
        "margin-md": "2rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-2xs": "0.125rem"
      },
      fontFamily: {
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "display-mobile": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        "data-label": ["JetBrains Mono", "monospace"],
        "data-metric-lg": ["JetBrains Mono", "monospace"],
        "data-metric-md": ["JetBrains Mono", "monospace"],
        "data-value": ["JetBrains Mono", "monospace"],
        badge: ["JetBrains Mono", "monospace"],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Courier New', 'monospace'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.06em", fontWeight: "500" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-xl": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-mobile": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        display: ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.03em", fontWeight: "700" }],
        "data-label": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "data-metric-lg": ["28px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "data-metric-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "data-value": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        badge: ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }]
      },
      animation: {
        'pulse-fast': 'pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 12s linear infinite',
        'radar': 'radar 3s linear infinite',
      },
      keyframes: {
        radar: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        }
      }
    },
  },
  plugins: [],
}
